//! Theme CSS loading service
//!
//! Reads the current theme CSS file generated by vulcan-theme.

use std::path::PathBuf;

/// Get the path to the current theme CSS file
pub fn get_theme_css_path() -> PathBuf {
    let home = std::env::var("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| dirs::home_dir().unwrap_or_default());

    home.join(".config/vulcan/current-theme.css")
}

/// Read the current theme CSS content
///
/// Returns the CSS content if the file exists, or None if not found.
/// This is designed to gracefully handle the case where no theme has been applied yet.
pub fn get_theme_css() -> Option<String> {
    let path = get_theme_css_path();
    std::fs::read_to_string(&path).ok()
}

/// Check if a theme CSS file exists (theme has been applied at least once)
pub fn has_theme_css() -> bool {
    get_theme_css_path().exists()
}
