# =============================================================================
# VulcanOS Kitty Terminal - Theme: ${THEME_NAME}
# Auto-generated by vulcan-theme - DO NOT EDIT DIRECTLY
# =============================================================================

# -----------------------------------------------------------------------------
# FONT CONFIGURATION
# -----------------------------------------------------------------------------
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size        11.0

# -----------------------------------------------------------------------------
# CURSOR & SCROLLBACK
# -----------------------------------------------------------------------------
cursor_shape          block
cursor_blink_interval 0.5
scrollback_lines 10000
wheel_scroll_multiplier 3.0

# -----------------------------------------------------------------------------
# WINDOW
# -----------------------------------------------------------------------------
window_padding_width  8
background_opacity 0.95
dynamic_background_opacity yes
confirm_os_window_close 0

# -----------------------------------------------------------------------------
# TAB BAR
# -----------------------------------------------------------------------------
tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
tab_bar_min_tabs        1
tab_activity_symbol     " "
tab_title_template      " {index}: {title} "
active_tab_title_template " {index}: {title} "
tab_bar_margin_width    4.0
tab_bar_margin_height   4.0 0.0
active_tab_font_style   bold
inactive_tab_font_style normal

# -----------------------------------------------------------------------------
# KEYBINDINGS
# -----------------------------------------------------------------------------
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+t new_tab
map ctrl+shift+q close_tab
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
map ctrl+shift+enter new_window
map ctrl+shift+w close_window
map ctrl+shift+h show_scrollback
map ctrl+shift+equal change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0

# -----------------------------------------------------------------------------
# THEME COLORS - ${THEME_NAME}
# -----------------------------------------------------------------------------
foreground              ${FG_PRIMARY}
background              ${BG_PRIMARY}
selection_foreground    ${BG_PRIMARY}
selection_background    ${ACCENT}

cursor                  ${CURSOR}
cursor_text_color       ${BG_PRIMARY}

url_color               ${ACCENT_ALT}

active_border_color     ${BORDER_ACTIVE}
inactive_border_color   ${BORDER_INACTIVE}
bell_border_color       ${RED}

active_tab_foreground   ${BG_PRIMARY}
active_tab_background   ${ACCENT}
inactive_tab_foreground ${FG_SECONDARY}
inactive_tab_background ${BG_SECONDARY}
tab_bar_background      ${BG_PRIMARY}

# Black
color0  ${BG_PRIMARY}
color8  ${BG_TERTIARY}

# Red
color1  ${RED}
color9  ${BRIGHT_RED}

# Green
color2  ${GREEN}
color10 ${BRIGHT_GREEN}

# Yellow
color3  ${YELLOW}
color11 ${BRIGHT_YELLOW}

# Blue
color4  ${BLUE}
color12 ${BRIGHT_BLUE}

# Magenta
color5  ${PURPLE}
color13 ${BRIGHT_PURPLE}

# Cyan
color6  ${CYAN}
color14 ${BRIGHT_CYAN}

# White
color7  ${FG_SECONDARY}
color15 ${FG_PRIMARY}

mark1_foreground ${BG_PRIMARY}
mark1_background ${ACCENT}
mark2_foreground ${BG_PRIMARY}
mark2_background ${ACCENT_ALT}
mark3_foreground ${BG_PRIMARY}
mark3_background ${GREEN}
