# =============================================================================
# VulcanOS Starship Prompt - Theme: ${THEME_NAME}
# Auto-generated by vulcan-theme - DO NOT EDIT DIRECTLY
# Traditional format: [user@host dir]$ with git info
# =============================================================================

format = """
[\\[](fg:${ACCENT})\
$username\
[@](fg:${FG_PRIMARY})\
$hostname\
[ ](fg:${FG_PRIMARY})\
$directory\
[\\]](fg:${ACCENT})\
$git_branch\
$git_status\
$character"""

right_format = """$cmd_duration"""
add_newline = false
command_timeout = 1000

[username]
show_always = true
style_user = "fg:${FG_PRIMARY} bold"
style_root = "fg:${RED} bold"
format = '[$user]($style)'

[hostname]
ssh_only = false
ssh_symbol = " "
style = "fg:${ACCENT_ALT} bold"
format = '[$ssh_symbol$hostname]($style)'
trim_at = "."

[directory]
style = "fg:${BLUE} bold"
format = '[$path]($style)[$read_only]($read_only_style)'
truncation_length = 3
truncation_symbol = ".../"
truncate_to_repo = true
read_only = " "
read_only_style = "fg:${RED}"
home_symbol = "~"

[git_branch]
symbol = " "
style = "fg:${PURPLE}"
format = '[ $symbol$branch(:$remote_branch)]($style)'
truncation_length = 20
truncation_symbol = "..."

[git_status]
style = "fg:${YELLOW}"
format = '[$all_status$ahead_behind]($style)'
conflicted = "=${count}"
ahead = "${count}"
behind = "${count}"
diverged = "${ahead_count}${behind_count}"
untracked = "?${count}"
stashed = "*${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "~${count}"
deleted = "-${count}"

[character]
success_symbol = '[\\$](bold fg:${GREEN})'
error_symbol = '[\\$](bold fg:${RED})'
vimcmd_symbol = '[\\$](bold fg:${YELLOW})'

[cmd_duration]
min_time = 2000
format = '[$duration]($style)'
style = "fg:${FG_MUTED}"

# Disabled modules
[aws]
disabled = true
[azure]
disabled = true
[battery]
disabled = true
[c]
disabled = true
[cmake]
disabled = true
[conda]
disabled = true
[container]
disabled = true
[dart]
disabled = true
[deno]
disabled = true
[docker_context]
disabled = true
[dotnet]
disabled = true
[elixir]
disabled = true
[elm]
disabled = true
[erlang]
disabled = true
[gcloud]
disabled = true
[git_commit]
disabled = true
[git_metrics]
disabled = true
[git_state]
disabled = true
[golang]
disabled = true
[gradle]
disabled = true
[haskell]
disabled = true
[helm]
disabled = true
[java]
disabled = true
[jobs]
disabled = true
[julia]
disabled = true
[kotlin]
disabled = true
[kubernetes]
disabled = true
[line_break]
disabled = true
[lua]
disabled = true
[memory_usage]
disabled = true
[nim]
disabled = true
[nix_shell]
disabled = true
[nodejs]
disabled = true
[ocaml]
disabled = true
[openstack]
disabled = true
[os]
disabled = true
[package]
disabled = true
[perl]
disabled = true
[php]
disabled = true
[pulumi]
disabled = true
[purescript]
disabled = true
[python]
disabled = true
[red]
disabled = true
[ruby]
disabled = true
[rust]
disabled = true
[scala]
disabled = true
[shell]
disabled = true
[shlvl]
disabled = true
[swift]
disabled = true
[terraform]
disabled = true
[time]
disabled = true
[vagrant]
disabled = true
[vlang]
disabled = true
[zig]
disabled = true
