<?xml version="1.0" encoding="UTF-8"?>
<!-- VulcanOS Launcher Icon - Theme: ${THEME_NAME} -->
<!-- Generated by vulcan-theme - do not edit manually -->
<svg width="48" height="48" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">
  <!-- 3x3 grid of rounded squares -->
  <rect x="4" y="4" width="10" height="10" rx="2" fill="${ACCENT}"/>
  <rect x="19" y="4" width="10" height="10" rx="2" fill="${ACCENT}"/>
  <rect x="34" y="4" width="10" height="10" rx="2" fill="${ACCENT}"/>

  <rect x="4" y="19" width="10" height="10" rx="2" fill="${ACCENT}"/>
  <rect x="19" y="19" width="10" height="10" rx="2" fill="${ACCENT}"/>
  <rect x="34" y="19" width="10" height="10" rx="2" fill="${ACCENT}"/>

  <rect x="4" y="34" width="10" height="10" rx="2" fill="${ACCENT}"/>
  <rect x="19" y="34" width="10" height="10" rx="2" fill="${ACCENT}"/>
  <rect x="34" y="34" width="10" height="10" rx="2" fill="${ACCENT}"/>
</svg>
