/* =============================================================================
 * VulcanOS Dock Theme - ${THEME_NAME}
 * Generated by vulcan-theme - do not edit manually
 * ============================================================================= */

window {
    background-color: rgba(${BG_PRIMARY_RGB}, 0.95);
    border-radius: 12px;
    border: 1px solid rgba(${BG_TERTIARY_RGB}, 0.5);
}

#box {
    padding: 8px 12px;
    background: transparent;
}

/* Active app indicator */
#active {
    border-bottom: solid 3px ${ACCENT_ALT};
}

button, image {
    background: none;
    background-color: transparent;
    border-style: none;
    box-shadow: none;
}

button {
    padding: 6px;
    margin-left: 4px;
    margin-right: 4px;
    border-radius: 8px;
}

/* Hover - Accent background */
button:hover {
    background-color: ${ACCENT};
    border-radius: 8px;
}

/* Focus state */
button:focus {
    box-shadow: none;
    background-color: ${BG_SECONDARY};
}

/* Active/pressed state */
button:active {
    background-color: ${ACCENT};
    opacity: 0.85;
}
