#!/bin/bash
# =============================================================================
# VulcanOS Installer - NVIDIA Configuration
# =============================================================================

run_nvidia_config() {
    is_done "nvidia" && { info "NVIDIA configuration already done, skipping"; return 0; }

    header "NVIDIA GPU configuration"

    # mkinitcpio — NVIDIA early KMS modules
    cat > /etc/mkinitcpio.conf << 'MKINITCPIO'
# =============================================================================
# VulcanOS - mkinitcpio Configuration (NVIDIA early KMS)
# Generated by VulcanOS installer
# =============================================================================

MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)
BINARIES=()
FILES=()
HOOKS=(base udev autodetect modconf kms block filesystems keyboard fsck)

COMPRESSION="zstd"
COMPRESSION_OPTIONS=(-c -T0 -19)
MKINITCPIO
    info "mkinitcpio.conf: NVIDIA early KMS modules"

    # NVIDIA modprobe — DRM modeset + framebuffer console
    mkdir -p /etc/modprobe.d
    cat > /etc/modprobe.d/nvidia.conf << 'MODPROBE'
# VulcanOS - NVIDIA DRM modeset + framebuffer
options nvidia_drm modeset=1 fbdev=1
MODPROBE
    info "modprobe: nvidia_drm modeset=1 fbdev=1"

    # GRUB kernel parameters
    local grub_default="/etc/default/grub"
    if [[ -f "$grub_default" ]]; then
        # nvidia-drm.modeset=1
        if ! grep -q 'nvidia-drm.modeset=1' "$grub_default"; then
            sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT="\(.*\)"/GRUB_CMDLINE_LINUX_DEFAULT="\1 nvidia-drm.modeset=1"/' "$grub_default"
            info "GRUB: added nvidia-drm.modeset=1"
        fi

        # Suspend/resume VRAM preservation
        if ! grep -q 'NVreg_PreserveVideoMemoryAllocations' "$grub_default"; then
            sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT="\(.*\)"/GRUB_CMDLINE_LINUX_DEFAULT="\1 nvidia.NVreg_PreserveVideoMemoryAllocations=1"/' "$grub_default"
            info "GRUB: added NVreg_PreserveVideoMemoryAllocations=1"
        fi
    else
        warn "/etc/default/grub not found — skipping kernel params"
    fi

    # NVIDIA pacman hook — auto-rebuild initramfs on nvidia/kernel updates
    mkdir -p /etc/pacman.d/hooks
    cat > /etc/pacman.d/hooks/nvidia.hook << 'HOOK'
[Trigger]
Operation = Install
Operation = Upgrade
Operation = Remove
Type = Package
Target = nvidia-open-dkms
Target = nvidia-utils
Target = linux
Target = linux-headers

[Action]
Description = Rebuilding initramfs after NVIDIA/kernel update...
Depends = mkinitcpio
When = PostTransaction
NeedsTargets
Exec = /usr/bin/mkinitcpio -P
HOOK
    info "Pacman hook: auto-rebuild initramfs on NVIDIA updates"

    # Enable NVIDIA power management services (suspend/hibernate/resume)
    for svc in nvidia-suspend nvidia-hibernate nvidia-resume; do
        if systemctl enable "$svc.service" 2>/dev/null; then
            info "Enabled: $svc"
        else
            warn "Could not enable $svc (nvidia-utils may not be installed yet)"
        fi
    done

    # Rebuild initramfs
    info "Rebuilding initramfs..."
    mkinitcpio -P

    # Regenerate GRUB
    if [[ -f "$grub_default" ]]; then
        info "Regenerating GRUB config..."
        grub-mkconfig -o /boot/grub/grub.cfg
    fi

    mark_done "nvidia"
    success "NVIDIA configuration complete"
}
